import sys

def main():
    tape = [0] * 30000  # Initialize tape

    tape[9] = 48
    print(chr(tape[9]), end='')
    tape[6] = 10
    print(chr(tape[6]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[12] = 49
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[12] = 51
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 49
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 57
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 53
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 51
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 53
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 55
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 54
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 55
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 55
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 56
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[15] = 57
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 49
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 49
    print(chr(tape[15]), end='')
    tape[12] = 53
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 57
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 51
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 53
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 54
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 55
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 56
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 57
    print(chr(tape[15]), end='')
    tape[12] = 51
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 50
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 49
    print(chr(tape[15]), end='')
    tape[12] = 49
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 51
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 53
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 54
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 55
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 56
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 57
    print(chr(tape[15]), end='')
    tape[12] = 49
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 51
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 49
    print(chr(tape[15]), end='')
    tape[12] = 51
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 51
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 54
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 55
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 56
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 57
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 52
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    tape[12] = 57
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 51
    print(chr(tape[15]), end='')
    tape[12] = 53
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 54
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 55
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 57
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 53
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 49
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 51
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    tape[12] = 55
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 54
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 55
    print(chr(tape[15]), end='')
    tape[12] = 55
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 57
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 54
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 53
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 55
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 56
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 55
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    tape[12] = 53
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 51
    print(chr(tape[15]), end='')
    tape[12] = 57
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 53
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 55
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 57
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 56
    print(chr(tape[18]), end='')
    tape[15] = 49
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 56
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    tape[12] = 54
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 54
    print(chr(tape[15]), end='')
    tape[12] = 52
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 56
    print(chr(tape[15]), end='')
    tape[12] = 51
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[18] = 57
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    tape[12] = 50
    print(chr(tape[12]), end='')
    tape[9] = 53
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 50
    print(chr(tape[15]), end='')
    tape[12] = 49
    print(chr(tape[12]), end='')
    tape[9] = 54
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 52
    print(chr(tape[15]), end='')
    tape[12] = 48
    print(chr(tape[12]), end='')
    tape[9] = 57
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 54
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 52
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    print(chr(tape[18]), end='')
    tape[15] = 56
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 49
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[21] = 49
    print(chr(tape[21]), end='')
    tape[18] = 48
    print(chr(tape[18]), end='')
    tape[15] = 48
    print(chr(tape[15]), end='')
    print(chr(tape[12]), end='')
    tape[9] = 48
    print(chr(tape[9]), end='')
    print(chr(tape[6]), end='')
    tape[1] = 203
    tape[6] = 2
    tape[7] = 1
    tape[9] = 1
    tape[10] = 1
    tape[12] = 0
    tape[13] = 9
    tape[15] = 2
    tape[16] = 1
    tape[18] = 0
    tape[19] = 1
    tape[21] = 1
    tape[22] = 1
    
    print()  # New line after program execution

if __name__ == "__main__":
    main()
        